version: "3.8"
services:
  mongodb:
    image: mongo:4.1
    container_name: mongodb
    ports:
      - 27017:27017
    # volumes:
    #   - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root